### ISSUE TITLE
Add support for user defined manifest files.

### ISSUE THREAD

**Issue by valencik** [astronomerdamo/OSXetup#2]
Each user likely wants different packages, we should enable configuration files for per user settings.

Example: user.brew
```
git
vim --with-python3
wget
```

The above manifest would install git, vim, and wget via brew. Additionally the `--with-python3` option would be passed to the brew install command.

**Comment by astronomerdamo** [comment]
Since we adopted brewdler users can govern their own brew/brew cask installs. I've added support for mackup which should restore users dotfiles/app prefs automatically. However, the recovery of user mackup files has yet to be implemented in bootstrap.sh.

**Comment by valencik** [comment]
I agree, I think brewdler solves this issue nicely. Closing.
